proxy_cache_path /var/cache/nginx/images
    levels=1:2
    keys_zone=image_cache:50m
    max_size=512m
    inactive=12h
    use_temp_path=off;

proxy_cache_path /var/cache/nginx/api
    levels=1:2
    keys_zone=api_cache:20m
    max_size=128m
    inactive=5m
    use_temp_path=off;
